version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: nish_drone_manager
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
